apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: ingress-{{ .Values.ingressname }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.servicename }}
            port:
              number: {{ .Values.serviceport }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.ingressname }}-certs-tls
