apiVersion: v1
stringData:
  "azure.json": |-
    {
        "cloud":"AzurePublicCloud",
        "tenantId": "{{ .Values.tenantId }}",
        "subscriptionId": "{{ .Values.subscriptionId }}",
        "resourceGroup": "{{ .Values.resourceGroup }}",
        "location": "{{ .Values.location }}",
        "aadClientId": "{{ .Values.clientId }}",
        "aadClientSecret": "{{ .Values.clientSecret }}",
        "useManagedIdentityExtension": false,
    }
kind: Secret
metadata:
  name: azure-cloud-provider
  namespace: {{ .Values.namespace }}
type: Opaque
