apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
      - name: crds.enabled
        value: "true"
      valueFiles:
      - values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.3
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
