apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      parameters:
      - name: controller.hostNetwork
        value: "true"
      - name: controller.service.type
        value: "ClusterIP"
      valueFiles:
      - values.yaml
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
